apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: machine_learning_engineering_interview
build:
  platforms: ["linux/amd64"]
  local:
    push: false
    useDockerCLI: true
    tryImportMissing: true
    useBuildkit: true
    concurrency: 0
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: api
      context: .
      docker:
        dockerfile: dockerfiles/Dockerfile.api
      sync:
        infer:
          - 'machine_learning_engineering_interview/api.py'
    - image: model
      context: .
      docker:
        dockerfile: dockerfiles/Dockerfile.model
      sync:
        infer:
          - 'machine_learning_engineering_interview/model.py'
    - image: loadtest
      context: .
      docker:
        dockerfile: dockerfiles/Dockerfile.loadtest
      sync:
        infer:
          - 'machine_learning_engineering_interview/loadtest.py'
manifests:
  helm:
    releases:
      - name: machine-learning-engineering-interview
        createNamespace: true
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        setValueTemplates:
          image_api.repository: "{{.IMAGE_REPO_api}}"
          image_api.tag: "{{.IMAGE_TAG_api}}"
          image_model.repository: "{{.IMAGE_REPO_model}}"
          image_model.tag: "{{.IMAGE_TAG_model}}"
        version: 0.1.0
deploy:
  kubeContext: minikube # see https://skaffold.dev/docs/environment/kube-context/
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: api-service
    port: 80
    localPort: 8080 # maps to the same port as docker-compose
  - resourceType: service
    resourceName: model-service
    port: 80
    localPort: 8000 # maps to the same port as docker-compose
verify:
- name: loadtest-verify
  container:
    name: loadtest-job
    image: loadtest
    command: ["locust", "-f", "loadtest.py"]
  executionMode:
    kubernetesCluster: {}
