apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtest-service
  namespace:  {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest-service
  template:
    metadata:
      labels:
        app: loadtest-service
    spec:
      containers:
        - name: loadtest-service
          image: {{ .Values.image_loadtest.repository }}:{{ .Values.image_loadtest.tag | default "latest" }}
          ports:
            - containerPort: 80
          command: ["locust", "-f", "loadtest.py", "--host", "http://model-service.{{ .Release.Namespace }}.svc.cluster.local:80", "--web-port", "8089"]
          env:
            - name: API_URL
              value: http://api-service.{{ .Release.Namespace }}.svc.cluster.local:80
          resources:
            requests:
              memory: "2Gi"
              cpu: 2
            limits:
              memory: "3Gi"
              cpu: 3
---
apiVersion: v1
kind: Service
metadata:
  name: loadtest-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: loadtest-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
  type: ClusterIP
