apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
  namespace:  {{ .Release.Namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
        - name: model-service
          image: {{ .Values.image_model.repository }}:{{ .Values.image_model.tag | default "latest" }}
          ports:
            - containerPort: 80
          command: ["/app/.venv/bin/fastapi", "run", "model.py", "--port", "8000", "--host", "0.0.0.0"]
          resources:
            requests:
              memory: "3Gi"
              nvidia.com/gpu: 0
              cpu: 2
            limits:
              memory: "4Gi"
              cpu: 3
              nvidia.com/gpu: 0

---
apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: model-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
